CREATE TABLE title_transaction (
    id UUID PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    idempotency_key VARCHAR(128) NOT NULL,
    request_hash CHAR(64) NOT NULL,
    vin CHAR(17) NOT NULL,
    jurisdiction CHAR(2) NOT NULL,
    transaction_type VARCHAR(32) NOT NULL,
    owner_full_name VARCHAR(160) NOT NULL,
    owner_email VARCHAR(254) NOT NULL,
    owner_address_line1 VARCHAR(200) NOT NULL,
    owner_city VARCHAR(100) NOT NULL,
    owner_state CHAR(2) NOT NULL,
    owner_postal_code VARCHAR(10) NOT NULL,
    purchase_price DECIMAL(12, 2),
    status VARCHAR(32) NOT NULL,
    external_reference VARCHAR(100),
    rejection_reason VARCHAR(500),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_title_transaction_idempotency UNIQUE (idempotency_key),
    CONSTRAINT ck_title_transaction_vin CHECK (CHAR_LENGTH(vin) = 17),
    CONSTRAINT ck_title_transaction_price CHECK (purchase_price IS NULL OR purchase_price >= 0)
);

CREATE INDEX idx_title_transaction_vin ON title_transaction (vin);
CREATE INDEX idx_title_transaction_status ON title_transaction (status);

CREATE TABLE transaction_audit_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id UUID NOT NULL,
    event_type VARCHAR(60) NOT NULL,
    from_status VARCHAR(32),
    to_status VARCHAR(32),
    channel VARCHAR(16) NOT NULL,
    actor VARCHAR(120) NOT NULL,
    details VARCHAR(2000),
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_audit_transaction FOREIGN KEY (transaction_id) REFERENCES title_transaction (id)
);

CREATE INDEX idx_audit_transaction_time
    ON transaction_audit_event (transaction_id, occurred_at);

CREATE TABLE outbox_event (
    id UUID PRIMARY KEY,
    aggregate_id UUID NOT NULL,
    event_type VARCHAR(80) NOT NULL,
    payload VARCHAR(4000) NOT NULL,
    status VARCHAR(20) NOT NULL,
    attempts INTEGER NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    published_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_outbox_transaction FOREIGN KEY (aggregate_id) REFERENCES title_transaction (id)
);

CREATE INDEX idx_outbox_delivery
    ON outbox_event (status, next_attempt_at);
